import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createDatabase,ids,rpcAs,asUser,appRoot} from './workspace-db.mjs';
process.env.C360_TEST_V14='1';
const db=await createDatabase(true);let checks=0;
const ok=(a,b)=>{assert.deepEqual(a,b);checks++};
const rejects=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++};
const owner=async(sql,args=[])=>{await db.exec('reset role');return db.query(sql,args)};
const save=(kind,data,user=ids.a,request=crypto.randomUUID())=>rpcAs(db,user,'workspace_save',[kind,JSON.stringify(data),request]);
const staffSave=(data,user=ids.a,request=crypto.randomUUID())=>rpcAs(db,user,'operations_save',['staff',JSON.stringify(data),request]);
const snap=(user=ids.a)=>rpcAs(db,user,'operations_snapshot');
const payload=r=>{const {organisation_id,user_id,...p}=r;return p};
let c=await save('client',{name:'Client one',contact:'Jane',contact_role:'Contracts manager',contacts:[]});
const other=await save('client',{name:'Other client',contacts:[]});
const foreign=await save('client',{name:'Foreign client',contacts:[]},ids.b);
const job=await save('job',{client_id:c.id,site:'Town site',contact_ids:[]});
const wrong=await save('job',{client_id:other.id,site:'Wrong client site',contact_ids:[]});
const foreignJob=await save('job',{client_id:foreign.id,site:'Foreign site',contact_ids:[]},ids.b);
ok((await snap()).clients.find(x=>x.id===c.id).contact_role,'Contracts manager');
let contact={id:crypto.randomUUID(),name:'Pat Contact',role:'Site manager',job_ids:[job.id]};
const p={...payload((await snap()).clients.find(x=>x.id===c.id)),contacts:[contact]},request=crypto.randomUUID();
const saved=await save('client',p,ids.ops,request);ok(await save('client',p,ids.ops,request),saved);
ok((await snap()).assignments.map(a=>a.contact_id),[contact.id]);
await rejects(async()=>save('job',{...payload((await snap()).jobs.find(x=>x.id===job.id)),version:1,contact_ids:[]}),/changed/);
for(const bad of [wrong.id,foreignJob.id,crypto.randomUUID()])await rejects(async()=>save('client',{...payload((await snap()).clients.find(x=>x.id===c.id)),contacts:[{...contact,job_ids:[bad]}]}),/belonging to this client/);
ok((await snap()).assignments.length,1);
const staleClient=payload((await snap()).clients.find(x=>x.id===c.id));
await save('job',{...payload((await snap()).jobs.find(x=>x.id===job.id)),contact_ids:[]});
await rejects(()=>save('client',{...staleClient,contacts:[contact]}),/changed/);
await save('client',{...payload((await snap()).clients.find(x=>x.id===c.id)),contacts:[]});
ok((await snap()).contacts.length,0);
const data={id:crypto.randomUUID(),full_name:'Renée Test',employment_role:'Operations',position:'Operations',hourly_rate:'25.50',qualifications:[]};
const staff=await staffSave(data,ids.ops);ok((await snap()).staff.find(s=>s.id===staff.id).hourly_rate,25.5);
ok((await snap()).staff.find(s=>s.id===staff.id).position,'Operations');
for(const rate of ['-1','1000','1.234','1e2','Infinity','12abc','0.001'])await rejects(()=>staffSave({...data,id:crypto.randomUUID(),hourly_rate:rate}),/Hourly rate/);
for(const rate of ['0','0.00','999','999.99','']){const r=await staffSave({...data,id:crypto.randomUUID(),hourly_rate:rate});ok((await snap()).staff.find(s=>s.id===r.id).hourly_rate,rate===''?null:Number(rate))}
for(const user of [ids.worker,ids.supervisor,ids.platform])await rejects(()=>staffSave(data,user),/Admin or Operations/);
let linked=(await snap()).staff.find(s=>s.user_id===ids.worker);
await staffSave({...payload(linked),position:'Operations',hourly_rate:'999.99'},ids.ops);
ok((await owner('select role from public.organisation_memberships where user_id=$1',[ids.worker])).rows[0].role,'operative');
ok(JSON.stringify(await snap(ids.worker)).includes('hourly_rate'),false);
ok(JSON.stringify(await snap(ids.supervisor)).includes('hourly_rate'),false);
const qualification=crypto.randomUUID(),imagePath=`${ids.orgA}/${staff.id}/${qualification}/${crypto.randomUUID()}.jpg`;
const images=[{path:imagePath,name:'Certificate.jpg'}];
let s=(await snap()).staff.find(x=>x.id===staff.id);
await rejects(()=>staffSave({...payload(s),qualifications:[{id:qualification,name:'CISRS',images}]}),/Upload.*before saving/);
await asUser(db,ids.ops,'insert into storage.objects(bucket_id,name) values($1,$2)',['staff-qualifications',imagePath]);
await staffSave({...payload(s),qualifications:[{id:qualification,name:'CISRS',reference:'ABC',images}]},ids.ops);
ok((await snap()).staff.find(x=>x.id===staff.id).qualifications[0].images,images);
for(const user of [ids.b,ids.worker,ids.supervisor,ids.platform]){
 ok((await asUser(db,user,'select * from storage.objects')).rows.length,0);
 await rejects(()=>asUser(db,user,'insert into storage.objects(bucket_id,name) values($1,$2)',['staff-qualifications',`${ids.orgA}/${staff.id}/${qualification}/${crypto.randomUUID()}.jpg`]),/row-level security/);
}
ok((await asUser(db,ids.ops,'select * from storage.objects')).rows.length,1);
ok((await asUser(db,ids.ops,'delete from storage.objects returning *')).rows.length,0);
ok((await asUser(db,ids.ops,"update storage.objects set name='bad' returning *")).rows.length,0);
await rejects(()=>asUser(db,ids.ops,'insert into storage.objects(bucket_id,name) values($1,$2)',['staff-qualifications',`${ids.orgA}/../bad.svg`]),/row-level security/);
s=(await snap()).staff.find(x=>x.id===staff.id);
await rejects(()=>staffSave({...payload(s),qualifications:[{id:qualification,name:'CISRS',images:[{...images[0],path:images[0].path.replace(staff.id,crypto.randomUUID())}]}]}),/Invalid qualification image/);
await rejects(()=>staffSave({...payload(s),qualifications:[{id:qualification,name:'CISRS',images:Array(6).fill(images[0])}]}),/five images/);
await owner('update public.organisations set status=$1 where id=$2',['suspended',ids.orgA]);
ok((await asUser(db,ids.a,'select * from storage.objects')).rows.length,0);
await owner('update public.organisations set status=$1 where id=$2',['active',ids.orgA]);
await db.exec(await fs.readFile(appRoot+'/supabase/migrations/20260906180341_client_staff_documents_v14.sql','utf8'));
ok((await snap()).staff.find(x=>x.id===staff.id).qualifications[0].images,images);
console.log(`PASS ${checks} v14 client/staff/storage assertions (isolated PostgreSQL; Storage transport emulated).`);await db.close();
