import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createDatabase,ids,rpcAs,asUser} from './workspace-db.mjs';
for(const v of [16,18,19,20])process.env['C360_TEST_V'+v]='1';
const db=await createDatabase();let n=0;
const check=(v,msg)=>{assert.ok(v,msg);n++;console.log('PASS',msg)};
const reject=async(fn,re=/required|unavailable|denied|invalid|policy|failed|changed|company/i)=>{await assert.rejects(fn,re);n++};
const call=(who,name,args=[])=>rpcAs(db,ids[who],name,args);
const change=(who,name,action,data,request=randomUUID())=>call(who,name,[action,JSON.stringify(data),request]);
const snap=who=>call(who,'operations_snapshot');
const feed=(who,before=null,limit=50)=>call(who,'notifications_snapshot',[before,limit]);
const saveJob=async(id,patch={},who='a',request=randomUUID())=>{const j=(await snap('a')).jobs.find(j=>j.id===id);delete j.organisation_id;return change(who,'workspace_save','job',{...j,contact_ids:[],...patch},request)};
try{
 const a=await snap('a'),worker=a.staff.find(s=>s.user_id===ids.worker),supervisor=a.staff.find(s=>s.user_id===ids.supervisor);
 const c=await change('a','workspace_save','client',{name:'Dashboard client',contacts:[]});
 const cB=await change('b','workspace_save','client',{name:'Other company',contacts:[]});
 const other=await change('b','workspace_save','job',{site:'SECRET B',client_id:cB.id,status:'Handover',contact_ids:[]});
 const j=await change('ops','workspace_save','job',{site:'Live site',site_address:'1 Site Road',client_id:c.id,status:'Delivery & Erection',notes:'OFFICE SECRET',supervisor_staff_id:supervisor.id,staff_ids:[worker.id],contact_ids:[]});
 check((await snap('a')).jobs.find(x=>x.id===j.id).staff_ids.includes(worker.id),'Office sees saved individuals');
 check((await snap('worker')).jobs.find(x=>x.id===j.id).site_address==='1 Site Road','Worker gets site address');
 check((await snap('worker')).jobs.find(x=>x.id===j.id).assigned_to_me,'Worker sees own job assignment');
 check((await snap('supervisor')).jobs.find(x=>x.id===j.id).assigned_to_me,'Supervisor assigned to job');
 check(!JSON.stringify(await snap('worker')).includes('OFFICE SECRET'),'No office notes in field snapshot');
 check(!(await snap('worker')).jobs.some(x=>x.id===other.id),'No cross-company basic jobs');
 check((await feed('a')).items.length===1&&(await feed('ops')).items.length===1,'Both office roles receive company event');
 check((await feed('worker')).items.length===1&&(await feed('supervisor')).items.length===1,'Assigned users receive job event');
 const unrelated=await change('a','workspace_save','job',{site:'Another live site',site_address:'2 Site Road',client_id:c.id,status:'Handover',contact_ids:[]});
 check((await snap('worker')).jobs.some(x=>x.id===unrelated.id&&x.is_live),'Unassigned workers can view all live jobs');
 check((await feed('worker')).items.length===1,'Unassigned users do not receive unrelated job events');
 check((await feed('a')).items.length===2,'Office sees unrelated company job updates');
 await saveJob(j.id,{notes:'NEW PRIVATE SECRET'});
 check((await feed('supervisor')).items.length===1,'Private note change produces no supervisor notification');
 check((await feed('a')).items[0].office_only,'Office-only change marked private');
 check(!JSON.stringify(await feed('a')).includes('NEW PRIVATE SECRET'),'Even office event does not duplicate private note content');
 const request=randomUUID();const current=(await snap('a')).jobs.find(x=>x.id===j.id);delete current.organisation_id;
 const data={...current,contact_ids:[],site_address:'Updated site address'};
 await change('a','workspace_save','job',data,request);const count=(await feed('supervisor')).items.length;
 await change('a','workspace_save','job',data,request);
 check((await feed('supervisor')).items.length===count,'Retry does not duplicate notifications');
 await reject(()=>change('worker','workspace_save','job',data));
 await reject(()=>saveJob(j.id,{supervisor_staff_id:randomUUID()}));
 await reject(()=>saveJob(j.id,{staff_ids:[randomUUID()]}));
 await reject(()=>saveJob(j.id,{site_address:'x'.repeat(1501)}),/too long/);
 check((await feed('supervisor')).items.length===count,'Rejected edits do not leave notifications');
 const first=(await feed('supervisor')).items[0];await call('supervisor','notifications_mark_read',[first.id,false]);
 check((await feed('supervisor')).items[0].read_at,'Read marking persists');
 check(!(await feed('worker')).items.find(x=>x.id===first.id).read_at,'Read status independent between users');
 await reject(async()=>call('worker','notifications_mark_read',[(await feed('a')).items.find(x=>x.office_only).id,false]));
 await reject(()=>call('b','notifications_mark_read',[first.id,true]));
 const page1=await feed('a',null,2),page2=await feed('a',page1.items.at(-1).id,2);
 check(page1.has_more&&page2.items.every(x=>!page1.items.some(y=>x.id===y.id)),'Cursor pagination is stable and non-overlapping');
 await call('worker','notifications_mark_read',[(await feed('worker')).latest_id,true]);check((await feed('worker')).unread_count===0,'Mark all only updates own visible notifications');
 check((await asUser(db,ids.worker,'select id,title,body from public.workspace_notifications')).rows.length===(await feed('worker')).items.length,'Direct table RLS matches field feed');
 await reject(()=>asUser(db,ids.worker,'select recipients from public.workspace_notifications'),/denied/);
 await reject(()=>asUser(db,ids.a,"insert into public.workspace_notifications(organisation_id,title,body,entity_kind) values($1,'forged','forged','job')",[ids.orgA]),/denied/);
 await reject(()=>asUser(db,ids.a,"select c360_private.notify($1,'forged','forged','job',null,'{}',false)",[ids.orgA]),/denied/);
 check((await asUser(db,ids.worker,'select * from public.job_staff_assignments')).rows.length===0,'No private staff roster table access for field users');
 const resources=await call('worker','job_resources_snapshot',[j.id]);
 check(resources.jobs.find(x=>x.id===j.id).site_address==='Updated site address','Files API also exposes basic site address');
 check(resources.jobs.every(x=>!('notes' in x)&&!('client_id' in x)&&!('staff_ids' in x)),'Basic projections exclude office and staff data');
 // Actual completed file changes, not just API stubs.
 await db.exec('reset role');
 const addFile=async(category)=>{const id=randomUUID();await db.query("insert into public.job_files(id,organisation_id,job_id,category,name,mime_type,byte_size,object_path,ready) values($1,$2,$3,$4,'SECRET filename','application/pdf',100,$5,false)",[id,ids.orgA,j.id,category,randomUUID()]);return id};
 const privateFile=await addFile('private'),rams=await addFile('rams');
 check((await feed('supervisor')).items.length===count,'Reserved uploads do not notify');
 await db.exec('reset role');await db.query('update public.job_files set ready=true where id=$1',[privateFile]);
 check((await feed('supervisor')).items.length===count,'Private file finish hidden from supervisor');
 await db.exec('reset role');await db.query('update public.job_files set ready=true where id=$1',[rams]);
 check((await feed('supervisor')).items[0].title==='New RAMS','New shared RAMS notifies supervisor');
 check((await call('worker','job_resources_snapshot',[j.id])).files.some(f=>f.id===rams),'Workers can read RAMS');
 check(!(await call('worker','job_resources_snapshot',[j.id])).files.some(f=>f.id===privateFile),'Workers cannot read private files');
 await db.exec('reset role');await db.query('update public.job_files set archived=true where id=$1',[rams]);
 check((await feed('supervisor')).items[0].title==='Shared job file removed','Shared file removal notifies supervisor');
 const v=await change('a','vehicle_save','vehicle',{version:0,registration:'AA20 ONE',name:'Assigned van',vehicle_type:'Van',availability:'Available',mileage:10,assigned_staff_id:worker.id});
 const v2=await change('a','vehicle_save','vehicle',{version:0,registration:'AA20 TWO',name:'Unassigned van',vehicle_type:'Van',availability:'Available',mileage:10});
 let fleet=await call('worker','vehicles_snapshot');
 check(fleet.vehicles.find(x=>x.id===v.id).assigned_to_me,'Assigned vehicle marked for worker');
 check(!fleet.vehicles.find(x=>x.id===v2.id).assigned_to_me,'Unassigned vehicle still visible');
 const checks=Object.fromEntries(['tyres','lights','brakes','steering','mirrors','wipers','horn','fluids','body_load','seatbelts','other'].map(k=>[k,'pass']));
 await change('worker','vehicle_save','inspection',{id:v2.id,mileage:10,confirmed:true,checks,notes:'',defect_details:''});
 check((await feed('worker')).items[0].title==='Vehicle inspection submitted','Worker can inspect another vehicle and receives own event');
 check(!(await feed('supervisor')).items.some(x=>x.entity_kind==='vehicle'),'Unrelated field users do not receive vehicle notifications');
 const vehicleEvents=(await feed('worker')).items.filter(x=>x.entity_kind==='vehicle').length;
 fleet=await call('a','vehicles_snapshot');await change('a','vehicle_save','vehicle',{...fleet.vehicles.find(x=>x.id===v.id),organisation_id:undefined,assigned_staff_id:null});
 check((await feed('worker')).items.filter(x=>x.entity_kind==='vehicle').length===vehicleEvents+1,'Removed vehicle assignee gets update');
 await change('worker','vehicle_save','inspection',{id:v2.id,mileage:11,confirmed:true,checks:{...checks,tyres:'fail'},defect_details:'Damaged tyre'});
 check((await feed('worker')).items[0].title==='Vehicle defects reported','Defect report notification');
 const history=await call('a','vehicle_history',[v2.id,0]);
 await change('ops','vehicle_save','resolve',{id:history.defects[0].id,confirmed:true,resolution:'Replaced tyre'});
 check((await feed('worker')).items[0].title==='Vehicle defect resolved','Reporter receives defect resolution notification');
 const booking=await change('a','operations_save','booking',{job_id:j.id,staff_ids:[worker.id],task:'Erection',starts_at:'2026-12-01T08:00',ends_at:'2026-12-01T12:00'});
 check((await feed('supervisor')).items[0].title==='Task updated','Job supervisor receives Planner changes without being in task crew');
 check((await feed('worker')).items[0].entity_kind==='planner','Planner crew gets task notification');
 await change('a','operations_save','cancel_booking',{id:booking.id,version:booking.version});
 check((await feed('supervisor')).items[0].title==='Task cancelled','Job supervisor receives task cancellation');
 const leave=await change('a','annual_leave_save','add',{staff_id:worker.id,starts_on:'2026-12-02',ends_on:'2026-12-03'});
 check((await feed('worker')).items[0].title==='Annual leave added','Own annual leave notified');
 check(!(await feed('supervisor')).items.some(x=>x.entity_kind==='staff'),'Other staff annual leave not exposed');
 await change('a','annual_leave_save','cancel',{id:leave.id,version:leave.version});
 check((await feed('worker')).items[0].title==='Annual leave cancelled','Leave cancellation notified');
 const scaffold=await change('a','scaffold_save','scaffold',{job_id:j.id,reference:'Front',location:'Front',description:'Test scaffold',erected_on:'2026-01-01'});
 check((await feed('supervisor')).items[0].title==='Scaffold inspection update','New scaffold notifies job supervisor');
 await change('worker','scaffold_save','flag',{id:scaffold.id,version:1,reason:'Check required'});
 check((await feed('supervisor')).items[0].body.endsWith('flag'),'Inspection requirement notifies supervisor');
 const beforeDraft=(await feed('worker')).items.length;
 const week='2026-08-31',entries=[{date:week,hours:8,notes:'PRIVATE TIMESHEET DETAIL'}];
 const sheet=await change('worker','timesheet_save','save',{version:0,week_start:week,entries});
 check((await feed('worker')).items.length===beforeDraft,'Daily timesheet drafts do not flood notifications');
 const submitted=await change('worker','timesheet_save','submit',{id:sheet.id,version:sheet.version,week_start:week,entries,confirmed:true});
 check((await feed('worker')).items[0].title==='Timesheet submitted','Own timesheet submission notification');
 check(!(await feed('supervisor')).items.some(x=>x.entity_kind==='timesheets'),'Supervisor cannot see other timesheets through notifications');
 await change('ops','timesheet_save','return',{id:sheet.id,version:submitted.version,reason:'PRIVATE REVIEW',confirmed:true});
 check((await feed('worker')).items[0].title==='Timesheet returned','Office review status delivered to owner');
 check(!JSON.stringify(await feed('worker')).includes('PRIVATE REVIEW')&&!JSON.stringify(await feed('a')).includes('PRIVATE TIMESHEET DETAIL'),'Notifications contain no timesheet notes or pay');
 await saveJob(j.id,{staff_ids:[],supervisor_staff_id:null});const removed=(await feed('supervisor')).items.length;
 await saveJob(j.id,{site_address:'Next address'});check((await feed('supervisor')).items.length===removed,'Removed supervisor receives no future job updates');
 await db.exec('reset role');await db.query('update public.organisation_memberships set is_active=false where user_id=$1',[ids.worker]);
 await reject(()=>feed('worker'));check((await asUser(db,ids.worker,'select id from public.workspace_notifications')).rows.length===0,'Disabled user loses table access');
 await db.exec('reset role');await db.query("update public.organisation_memberships set role='operative' where user_id=$1",[ids.ops]);
 check(!(await feed('ops')).items.some(x=>x.office_only),'Role downgrade removes office-only notifications');
 check(!JSON.stringify(await feed('b')).includes('Live site'),'Other company never sees notifications');
 console.log(`PASS v20 dashboard: ${n} checks`);
}finally{await db.close()}
