import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createDatabase,ids,asUser,rpcAs,appRoot} from './workspace-db.mjs';
const db=await createDatabase(true);let checks=0;
const ok=(actual,expected)=>{assert.deepEqual(actual,expected);checks++};
const rejects=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++};
const owner=async(sql,args=[])=>{await db.exec('reset role');return db.query(sql,args)};
const snap=(user=ids.a)=>rpcAs(db,user,'operations_snapshot');
const save=(kind,data,user=ids.a,req=crypto.randomUUID())=>rpcAs(db,user,'operations_save',[kind,JSON.stringify(data),req]);
const oldSave=(kind,data,user=ids.a)=>rpcAs(db,user,'workspace_save',[kind,JSON.stringify(data),crypto.randomUUID()]);
const payload=row=>{const {organisation_id,user_id,...data}=row;return data};
let initial=await snap();ok(initial.staff.length,2);
const worker=initial.staff.find(s=>s.user_id===ids.worker),sup=initial.staff.find(s=>s.user_id===ids.supervisor);
const manual={full_name:'Manual Worker',email:'manual@example.test',employment_role:'Operative',availability:'Available',qualifications:[{name:'CISRS',reference:'CARD-1',expires:'2027-05-01'}]};
const request=crypto.randomUUID(),created=await save('staff',manual,ids.ops,request);
ok(await save('staff',manual,ids.ops,request),created);
await rejects(()=>save('staff',{...manual,full_name:'Changed'},ids.ops,request),/Request changed/);
await rejects(()=>save('staff',{...manual,organisation_id:ids.orgB}),/assigned by the server/);
await rejects(()=>save('staff',{...manual,user_id:ids.worker}),/assigned by the server/);
await rejects(()=>save('staff',{...manual,qualifications:[{name:'Bad',expires:'not-a-date'}]}),/date/);
await rejects(()=>save('staff',manual,ids.worker),/Admin or Operations/);
await rejects(()=>save('staff',manual,ids.supervisor),/Admin or Operations/);
await rejects(()=>save('staff',manual,ids.platform),/Admin or Operations/);
await rejects(()=>save('staff',{...payload(worker),is_active:false},ids.ops),/Company Admin/);
await rejects(()=>save('staff',{...payload(worker),employment_role:'Scaffold Supervisor'},ids.ops),/Company Admin/);
await rejects(()=>save('staff',{...payload(worker),full_name:'Impersonation'},ids.ops),/Linked name/);
const bstaff=await save('staff',manual,ids.b);
await rejects(()=>save('staff',{...manual,id:bstaff.id,version:1}),/unavailable/);
const c=await oldSave('client',{name:'Private Client',notes:'CLIENT_SECRET',contacts:[]});
const j=await oldSave('job',{client_id:c.id,site:'River Site',notes:'JOB_SECRET',contact_ids:[],start_date:'2090-01-01',end_date:'2090-01-31',status:'Acceptance & Planning'});
const teamData={name:'Team North',supervisor_id:sup.id,staff_ids:[worker.id],notes:'TEAM_SECRET'};
const team=await save('team',teamData,ids.ops);
await rejects(()=>save('team',{...teamData,name:'Bad Team',staff_ids:[bstaff.id]}),/unavailable/);
await rejects(()=>save('team',{...teamData,name:'Bad Supervisor',supervisor_id:worker.id}),/Scaffold Supervisor/);
await rejects(()=>save('team',{...teamData,name:'team north'}),/unique/);
const booking={job_id:j.id,team_id:team.id,team_version:1,staff_ids:[],starts_at:'2090-01-03T08:00',ends_at:'2090-01-03T16:00',task:'Erect scaffold',instructions:'Meet at the north gate'};
const br=crypto.randomUUID(),b=await save('booking',booking,ids.ops,br);
ok(await save('booking',booking,ids.ops,br),b);
ok((await snap()).crew.filter(a=>a.booking_id===b.id).length,2);
await rejects(()=>save('booking',{...booking,team_id:null,staff_ids:[worker.id],starts_at:'2090-01-03T12:00'}),/Scheduling conflict/);
await rejects(()=>save('booking',{...booking,team_id:null,staff_ids:[bstaff.id]}),/belong to this company/);
await rejects(()=>save('booking',{...booking,starts_at:'2089-12-31T08:00',ends_at:'2089-12-31T16:00'}),/job dates/);
await rejects(()=>save('booking',{...booking,ends_at:booking.starts_at}),/start and finish/);
await rejects(()=>save('booking',{...booking,team_id:null,staff_ids:[]}),/at least one/);
const adjacent=await save('booking',{...booking,starts_at:'2090-01-03T16:00',ends_at:'2090-01-03T17:00'});
const workerView=await snap(ids.worker),superView=await snap(ids.supervisor);
ok(workerView.bookings.length,2);ok(workerView.staff.length,1);ok(superView.staff.length,2);
ok(workerView.clients.length,0);ok(workerView.jobs.length,1);
ok(JSON.stringify(workerView).includes('_SECRET'),false);ok(JSON.stringify(superView).includes('_SECRET'),false);
ok(workerView.bookings[0].instructions,'Meet at the north gate');
for(const table of ['staff_members','teams','team_members','planner_bookings','planner_assignments','clients','jobs']){
  for(const user of [ids.worker,ids.supervisor,ids.platform])ok((await asUser(db,user,'select * from public.'+table)).rows.length,0);
  ok((await asUser(db,ids.b,'select * from public.'+table)).rows.every(r=>r.organisation_id===ids.orgB),true);
  await rejects(()=>asUser(db,ids.ops,'delete from public.'+table),/permission denied/);
}
await rejects(()=>snap(ids.platform),/Active company/);
const srow=(await snap()).staff.find(s=>s.id===created.id);
await save('staff',{...payload(srow),phone:'01234',notes:'STAFF_SECRET'},ids.ops);
await rejects(()=>save('staff',{...payload(srow),phone:'OLD'}),/changed/);
await save('team',{...teamData,id:team.id,version:1,staff_ids:[created.id]},ids.ops);
// Existing bookings retain their original crew; changing a team is not retroactive.
ok((await snap()).crew.filter(a=>a.booking_id===b.id).map(a=>a.staff_id).sort(),[worker.id,sup.id].sort());
await rejects(()=>save('booking',{...booking,starts_at:'2090-01-04T08:00',ends_at:'2090-01-04T16:00'}),/roster changed/);
const next=await save('booking',{...booking,team_version:2,starts_at:'2090-01-04T08:00',ends_at:'2090-01-04T16:00'});
ok((await snap(ids.worker)).bookings.length,2);
await rejects(()=>save('booking',{...booking,id:b.id,version:99,team_version:2}),/changed/);
await save('cancel_booking',{id:b.id,version:1});
ok((await snap(ids.worker)).bookings.length,1);
await rejects(()=>save('cancel_booking',{id:next.id,version:1},ids.b),/unavailable/);
await rejects(async()=>oldSave('job',{...payload((await snap()).jobs[0]),contact_ids:[],archived:true}),/scheduled bookings/);
await owner('update public.organisation_memberships set is_active=false where user_id=$1',[ids.supervisor]);
await rejects(()=>snap(ids.supervisor),/Active company/);
ok((await snap()).staff.find(s=>s.id===sup.id).is_active,false);
await rejects(()=>save('booking',{...booking,team_version:2,starts_at:'2090-01-05T08:00',ends_at:'2090-01-05T16:00'}),/active supervisor/);
await owner('update public.organisation_memberships set is_active=true where user_id=$1',[ids.supervisor]);
await owner("update public.organisations set status='suspended' where id=$1",[ids.orgA]);
await rejects(()=>snap(),/Active company/);await rejects(()=>save('staff',manual,ids.ops,request),/Active company/);
await owner("update public.organisations set status='active' where id=$1",[ids.orgA]);
await owner("update auth.users set raw_user_meta_data='{"+'"needs_password_setup":true'+"}' where id=$1",[ids.worker]);
await rejects(()=>snap(ids.worker),/Active company/);
await owner("update auth.users set raw_user_meta_data='{}' where id=$1",[ids.worker]);
// Reserved invitation transaction creates exactly one correctly named linked staff.
const invitedId=crypto.randomUUID();
const invitation=(await asUser(db,ids.a,"select public.prepare_company_user_invite('invited@example.test','New Site Supervisor','supervisor') as id")).rows[0].id;
await asUser(db,ids.a,'select public.claim_company_invitation($1)',[invitation]);
await owner("insert into auth.users(id,email,invited_at) values($1,'invited@example.test',now())",[invitedId]);
let invited=(await snap()).staff.find(s=>s.user_id===invitedId);
ok(invited.full_name,'New Site Supervisor');ok(invited.employment_role,'Scaffold Supervisor');
await rejects(()=>snap(invitedId),/Active company/);
await owner('update auth.users set invited_at=now() where id=$1',[invitedId]);
ok((await snap()).staff.filter(s=>s.user_id===invitedId).length,1);
await owner("update auth.users set email_confirmed_at=now(),raw_user_meta_data='{}' where id=$1",[invitedId]);
ok((await snap(invitedId)).bookings.length,0);
await owner("update public.profiles set full_name='Updated Staff Name' where id=$1",[invitedId]);
ok((await snap()).staff.find(s=>s.user_id===invitedId).full_name,'Updated Staff Name');
// Archive hides assignments without changing login status; restore does not grant a new role.
const workerNow=(await snap()).staff.find(s=>s.id===worker.id);
await save('staff',{...payload(workerNow),archived:true});
ok((await snap(ids.worker)).bookings.length,0);
const workerArchived=(await snap()).staff.find(s=>s.id===worker.id);
await save('staff',{...payload(workerArchived),archived:false});
ok((await snap(ids.worker)).bookings.length,1);
// Raw writes and explicit cross-company FK links are rejected.
await rejects(()=>asUser(db,ids.ops,"insert into public.teams(organisation_id,name,supervisor_id) values($1,'Bypass',$2)",[ids.orgA,sup.id]),/permission denied/);
await rejects(()=>asUser(db,ids.ops,"update public.staff_members set user_id=$1 where id=$2",[ids.ops,created.id]),/permission denied/);
await rejects(()=>owner("insert into public.team_members(organisation_id,team_id,staff_id) values($1,$2,$3)",[ids.orgA,team.id,bstaff.id]),/foreign key/);
// Deleting an Auth user keeps booking history but unlinks and archives their staff.
await owner('delete from auth.users where id=$1',[ids.worker]);
const retired=(await snap()).staff.find(s=>s.id===worker.id);
ok(retired.user_id,null);ok(retired.archived,true);ok(retired.is_active,false);ok(retired.email,'');
ok((await snap()).crew.some(a=>a.staff_id===worker.id),true);
await owner("update public.organisation_memberships set role='operations' where user_id=$1",[ids.supervisor]);
ok((await snap()).staff.find(s=>s.id===sup.id).archived,true);
await owner('set role anon');await rejects(()=>db.query('select public.operations_snapshot()'),/permission denied/);
await rejects(()=>db.query("select public.operations_save('staff','{}',gen_random_uuid())"),/permission denied/);
await owner('reset role');await db.exec(await fs.readFile(appRoot+'/supabase/migrations/006_staff_teams_planner.sql','utf8'));
ok((await snap()).staff.find(s=>s.id===worker.id).archived,true);
ok((await snap()).bookings.length,3);
console.log(`PASS ${checks} combined operations assertions: tenancy, role projections, private fields, staff lifecycle, frozen rosters, conflicts, retries, dates, stale edits, suspension, deletion and migration rerun.`);
await db.close();
