import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createDatabase,ids,rpcAs,asUser} from './workspace-db.mjs';
process.env.C360_TEST_V16='1';process.env.C360_TEST_V18='1';process.env.C360_TEST_V19='1';
const db=await createDatabase();let n=0;
const check=(v,msg)=>{assert.ok(v,msg);n++};
const reject=async(fn,re=/required|unavailable|denied|invalid|policy|failed|changed/i)=>{await assert.rejects(fn,re);n++};
const call=(who,name,args=[])=>rpcAs(db,ids[who],name,args);
const change=(who,name,action,data,request=randomUUID())=>call(who,name,[action,JSON.stringify(data),request]);
const snap=who=>call(who,'operations_snapshot');
try{
 const a=await snap('a'),worker=a.staff.find(s=>s.user_id===ids.worker),supervisor=a.staff.find(s=>s.user_id===ids.supervisor);
 const c=await change('a','workspace_save','client',{name:'v19 client',contacts:[]});
 const job=await change('a','workspace_save','job',{site:'Morning site',client_id:c.id,status:'Quotation',contact_ids:[]});
 const job2=await change('a','workspace_save','job',{site:'Afternoon site',client_id:c.id,status:'Quotation',contact_ids:[]});
 const saveJob=async(id,status)=>{const j=(await snap('a')).jobs.find(j=>j.id===id);return change('a','workspace_save','job',{...j,organisation_id:undefined,status,contact_ids:[]})};
 await saveJob(job2.id,'Completed');check((await snap('a')).jobs.find(j=>j.id===job2.id).status==='Completion/Closed','Old Completed normalised');await saveJob(job2.id,'Quotation');
 const scaffold=await change('a','scaffold_save','scaffold',{job_id:job.id,reference:'Front',location:'Front',description:'Tied scaffold',erected_on:'2026-01-01'});
 await db.exec('reset role');await db.query('update public.job_scaffolds set inspection_required=false where id=$1',[scaffold.id]);
 await saveJob(job.id,'Handover');let sc=(await call('worker','scaffold_snapshot')).scaffolds.find(s=>s.id===scaffold.id);
 check(sc.inspection_required&&sc.required_reason==='Handover inspection required'&&sc.required_at,'Handover flags existing scaffold');
 const version=sc.version;await saveJob(job.id,'Handover');check((await call('a','scaffold_snapshot')).scaffolds[0].version===version,'Same status does not retrigger');
 const keys=['foundations','standards','bracing','ties','platforms','edge_protection','access','loading','design','surroundings'];
 const inspection={id:sc.id,version:sc.version,inspected_at:'2026-02-01T12:00:00Z',confirmed:true,checks:Object.fromEntries(keys.map(k=>[k,'pass'])),outcome:'safe',reason:'initial',inspection_for:'Client address',inspector_position:'Operative',findings:'None',action_taken:'None',further_action:'None'};
 await reject(()=>change('worker','scaffold_save','inspect',inspection),/after the latest reported event/);
 inspection.inspected_at=new Date().toISOString();await change('worker','scaffold_save','inspect',inspection);check(!(await call('a','scaffold_snapshot')).scaffolds[0].inspection_required,'Post-handover report resolves requirement');
 await saveJob(job.id,'Delivery & Erection');await saveJob(job.id,'Handover');check((await call('a','scaffold_snapshot')).scaffolds[0].inspection_required,'Re-entering handover requires fresh inspection');
 await saveJob(job2.id,'Handover & Initial Inspection');check((await snap('a')).jobs.find(j=>j.id===job2.id).status==='Handover','Legacy handover name accepted');
 check((await call('worker','scaffold_snapshot')).handover_pending.some(j=>j.id===job2.id),'Job without scaffold appears as pending');
 check(!(await call('b','scaffold_snapshot')).handover_pending.length,'Pending handovers isolated by company');
 await change('a','scaffold_save','scaffold',{job_id:job2.id,reference:'Rear',location:'Rear',description:'Independent',erected_on:'2026-01-01'});
 check(!(await call('a','scaffold_snapshot')).handover_pending.some(j=>j.id===job2.id),'Registration resolves job placeholder');
 check((await call('a','scaffold_snapshot')).scaffolds.find(s=>s.job_id===job2.id).inspection_required,'Actual scaffold still needs inspection');
 const booking={id:randomUUID(),version:0,job_id:job.id,staff_ids:[worker.id],task:'Morning task',starts_at:'2026-10-05T08:00',ends_at:'2026-10-05T12:00'};
 await change('a','operations_save','booking',booking);
 await change('ops','operations_save','booking',{...booking,id:randomUUID(),job_id:job2.id,task:'Afternoon task',starts_at:'2026-10-05T12:00',ends_at:'2026-10-05T16:00'});
 check((await snap('a')).bookings.length===2&&(await snap('worker')).bookings.length===2,'Multiple tasks same day visible to office and assigned worker');
 await reject(()=>change('a','operations_save','booking',{...booking,id:randomUUID()}),/Scheduling conflict/);
 const leaveData={staff_id:worker.id,starts_on:'2026-10-05',ends_on:'2026-10-07'},req=randomUUID();
 const leave=await change('ops','annual_leave_save','add',leaveData,req);
 check((await change('ops','annual_leave_save','add',leaveData,req)).id===leave.id,'Leave save retry idempotent');
 check((await snap('a')).bookings.length===2,'Existing tasks retained when leave added');
 check((await snap('worker')).annual_leave.length===1&&(await snap('supervisor')).annual_leave.length===0,'Field roles only see their own leave');
 check((await snap('b')).annual_leave.length===0,'Other company sees no leave');
 check((await asUser(db,ids.worker,'select * from public.staff_annual_leave')).rows.length===1,'Direct RLS own leave');
 check((await asUser(db,ids.supervisor,'select * from public.staff_annual_leave')).rows.length===0,'Direct RLS excludes colleagues leave');
 for(const who of ['worker','supervisor','platform'])await reject(()=>change(who,'annual_leave_save','add',leaveData));
 await reject(()=>change('b','annual_leave_save','add',leaveData));
 await reject(()=>change('a','annual_leave_save','add',leaveData),/already covers/);
 await reject(()=>change('a','annual_leave_save','add',{...leaveData,ends_on:'2026-10-01'}),/dates in order/);
 await reject(()=>change('a','operations_save','booking',{...booking,id:randomUUID(),starts_at:'2026-10-07T08:00',ends_at:'2026-10-07T09:00'}),/annual leave/);
 await change('a','operations_save','booking',{...booking,id:randomUUID(),starts_at:'2026-10-08T08:00',ends_at:'2026-10-08T09:00'});
 check((await snap('a')).bookings.length===3,'Inclusive leave end boundary and failed booking rollback');
 await reject(()=>change('b','annual_leave_save','cancel',{id:leave.id,version:1}));
 await change('a','annual_leave_save','cancel',{id:leave.id,version:1});check((await snap('worker')).annual_leave.length===0,'Cancelled leave removed from planner');
 await reject(()=>change('a','annual_leave_save','cancel',{id:leave.id,version:1}));
 await db.exec('reset role');check((await db.query('select cancelled_at from public.staff_annual_leave where id=$1',[leave.id])).rows[0].cancelled_at,'Cancelled leave retained');
 const photo=`${ids.orgA}/${worker.id}/${randomUUID()}.jpg`;
 await asUser(db,ids.a,"insert into storage.objects(bucket_id,name) values('staff-profiles',$1)",[photo]);
 check((await asUser(db,ids.ops,"select * from storage.objects where bucket_id='staff-profiles'")).rows.length===1,'Operations can view profile photo');
 for(const who of ['worker','supervisor','b']){
  check((await asUser(db,ids[who],"select * from storage.objects where bucket_id='staff-profiles'")).rows.length===0,'Private profile photo '+who);
  await reject(()=>asUser(db,ids[who],"insert into storage.objects(bucket_id,name) values('staff-profiles',$1)",[`${ids.orgA}/${worker.id}/${randomUUID()}.jpg`]));
 }
 const staffData={...worker,user_id:undefined,organisation_id:undefined,address:'10 Test Street',profile_photo:photo,position:'Operative',hourly_rate:'25.50'};const staffReq=randomUUID();
 await change('a','operations_save','staff',staffData,staffReq);let saved=(await snap('ops')).staff.find(s=>s.id===worker.id);
 check(saved.address==='10 Test Street'&&saved.profile_photo===photo,'Profile personal fields saved');
 const safe=(await snap('worker')).staff.find(s=>s.id===worker.id);check(!('address' in safe)&&!('profile_photo' in safe)&&!('hourly_rate' in safe),'Worker snapshot does not leak personal or pay fields');
 await change('a','operations_save','staff',{...staffData,version:saved.version,address:'20 Updated Street'});
 await change('a','operations_save','staff',staffData,staffReq);check((await snap('a')).staff.find(s=>s.id===worker.id).address==='20 Updated Street','Old staff request retry cannot overwrite newer address');
 saved=(await snap('a')).staff.find(s=>s.id===worker.id);
 await reject(()=>change('a','operations_save','staff',{...staffData,version:saved.version,profile_photo:`${ids.orgB}/${worker.id}/${randomUUID()}.jpg`}),/photo/);
 await reject(()=>change('a','operations_save','staff',{...staffData,id:supervisor.id,version:supervisor.version}),/photo/);
 await reject(()=>asUser(db,ids.a,'select c360_private.operations_save_v14($1,$2::jsonb,$3::uuid)',['staff',JSON.stringify(staffData),randomUUID()]));
 await db.exec('reset role');await db.query("update public.organisations set status='suspended' where id=$1",[ids.orgA]);
 await reject(()=>snap('a'));await reject(()=>change('a','annual_leave_save','add',leaveData));
 console.log(`PASS profiles/planner/handover v19: ${n} assertions`);
}finally{await db.close()}
