import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createDatabase,ids,rpcAs,asUser} from './workspace-db.mjs';
process.env.C360_TEST_V16='1';const db=await createDatabase();let count=0;
const check=(value,msg)=>{assert.ok(value,msg);count++};const rejects=async(fn,pattern)=>{await assert.rejects(fn,pattern);count++};
const week='2026-08-31';
const snap=who=>rpcAs(db,ids[who],'timesheets_snapshot',[week]);
const save=(who,action,data,request=randomUUID())=>rpcAs(db,ids[who],'timesheet_save',[action,JSON.stringify(data),request]);
const hist=(who,id)=>rpcAs(db,ids[who],'timesheet_history',[id]);
const draft={week_start:week,version:0,entries:[{date:week,hours:8,notes:'Monday work'}]};
try{
 const worker=(await snap('worker')).self_staff,supervisor=(await snap('supervisor')).self_staff;
 check(worker&&supervisor,'Linked profiles');check((await snap('worker')).staff.length===0,'No other staff directory');
 const officeSave=(who,rpc,kind,data)=>rpcAs(db,ids[who],rpc,[kind,JSON.stringify(data),randomUUID()]);
 const client=await officeSave('a','workspace_save','client',{name:'Timesheet client',contacts:[]});
 const job=await officeSave('a','workspace_save','job',{client_id:client.id,site:'Assigned test site',status:'Quotation',contact_ids:[]});
 const otherJob=await officeSave('a','workspace_save','job',{client_id:client.id,site:'Private unassigned site',status:'Quotation',contact_ids:[]});
 await officeSave('a','operations_save','booking',{job_id:job.id,staff_ids:[worker.id],starts_at:week+'T08:00',ends_at:week+'T16:00',task:'Work'});
 check((await snap('worker')).jobs.length===1&&(await snap('worker')).jobs[0].id===job.id,'Only own assigned jobs offered');
 check((await snap('supervisor')).jobs.length===0,'Supervisor cannot see worker job options');
 await rejects(()=>save('worker','save',{...draft,entries:[{date:week,hours:8,job_id:otherJob.id}]}),/available job/);
 const bc=await officeSave('b','workspace_save','client',{name:'Other company client',contacts:[]});
 const bj=await officeSave('b','workspace_save','job',{client_id:bc.id,site:'Other company site',status:'Quotation',contact_ids:[]});
 await rejects(()=>save('worker','save',{...draft,entries:[{date:week,hours:8,job_id:bj.id}]}),/available job/);
 draft.entries[0].job_id=job.id;
 await db.exec('reset role');await db.query('update public.staff_members set hourly_rate=$1 where id in ($2,$3)',[25.50,worker.id,supervisor.id]);
 const request=randomUUID(),first=await save('worker','save',draft,request);
 check(first.status==='draft','Save does not submit');check((await save('worker','save',draft,request)).id===first.id,'Save retry');
 await rejects(()=>save('worker','save',{...draft,entries:[]},request),/Request changed/);
 let w=(await snap('worker')).sheets[0];check(w.total_hours===8||Number(w.total_hours)===8,'Saved hours');
 check(w.entries[0].job_label.includes('Assigned test site'),'Server supplies saved job label');
 check(!('hourly_rate' in w)&&!('gross_estimate' in w)&&!('rate_captured_at' in w),'No pay keys in worker response');
 check((await snap('supervisor')).sheets.length===0,'Supervisor cannot see worker');
 await rejects(()=>hist('supervisor',w.id),/unavailable/);
 await rejects(()=>hist('b',w.id),/unavailable/);
 check((await asUser(db,ids.supervisor,'select * from public.timesheets where id=$1',[w.id])).rows.length===0,'Direct RLS blocks coworker');
 for(const who of ['a','ops']){const d=await snap(who);check(d.sheets.length===1&&Number(d.sheets[0].hourly_rate)===25.5,'Office sees sheet and pay '+who)}
 await rejects(()=>save('ops','approve',{id:w.id,version:w.version,confirmed:true,expected_rate:25.5}),/Only submitted/);
 await rejects(()=>save('supervisor','save',{...draft,id:w.id,version:w.version}),/changed or unavailable/);
 await rejects(()=>save('worker','save',{...draft,staff_id:supervisor.id}),/assigned by the server/);
 await rejects(()=>save('worker','save',{...draft,hourly_rate:999}),/assigned by the server/);
 const second={id:w.id,version:w.version,week_start:week,entries:[...draft.entries,{date:'2026-09-01',hours:7.5,notes:'Tuesday'}]};
 const saved=await save('worker','save',second);check(saved.status==='draft','Daily save remains draft');
 await rejects(()=>save('worker','save',second),/changed or unavailable/);
 w=(await snap('worker')).sheets[0];check(Number(w.total_hours)===15.5,'Weekly total');
 const current={...second,version:w.version};
 for(const entries of [[{date:week,hours:7.25}],[{date:week,hours:8.1}],[{date:week,hours:100}],[{date:week,hours:24.5}],[{date:week,hours:-1}],[{date:week,hours:25}],[{date:week,hours:'NaN'}],[{date:week,hours:8.001}],[{date:week,hours:14},{date:week,hours:14}],[{date:'2026-09-07',hours:8}],[{date:week,hours:8,notes:'x'.repeat(1001)}]])await rejects(()=>save('worker','save',{...current,entries}),/daily hours|at most/);
 await rejects(()=>save('worker','save',{...current,entries:[{date:week,hours:8,job_id:randomUUID()}]}),/available job/);
 await rejects(()=>save('worker','submit',{...current,confirmed:false}),/confirm/);
 await rejects(()=>save('worker','submit',{...current,entries:[],confirmed:true}),/some worked hours/);
 await rejects(()=>save('worker','save',{...draft,week_start:'2026-09-01'}),/Monday/);
 const submitted=await save('worker','submit',{...current,confirmed:true});check(submitted.status==='submitted','Explicit submit');
 await rejects(()=>save('worker','save',{...current,version:submitted.version}),/locked/);
 for(const who of ['worker','supervisor'])await rejects(()=>save(who,'approve',{id:w.id,version:submitted.version,confirmed:true,expected_rate:25.5}),/Admin or Operations/);
 await rejects(()=>save('b','approve',{id:w.id,version:submitted.version,confirmed:true,expected_rate:25.5}),/unavailable/);
 await rejects(()=>save('a','return',{id:w.id,version:submitted.version,reason:''}),/reason/);
 const returned=await save('ops','return',{id:w.id,version:submitted.version,reason:'Check Tuesday hours'});check(returned.status==='returned','Office return');
 check((await snap('worker')).sheets[0].review_note==='Check Tuesday hours','Owner sees return reason');
 const corrected={...current,version:returned.version,entries:[{date:week,hours:8},{date:'2026-09-01',hours:8}]};
 const resaved=await save('worker','save',corrected);check(resaved.status==='draft','Returned sheet can save daily again');
 const resubmitted=await save('worker','submit',{...corrected,version:resaved.version,confirmed:true});
 await rejects(()=>save('a','approve',{id:w.id,version:resubmitted.version,expected_rate:20,confirmed:true}),/rate changed/);
 await rejects(()=>save('a','approve',{id:w.id,version:resubmitted.version,expected_rate:25.5,confirmed:false}),/Confirm/);
 const approval={id:w.id,version:resubmitted.version,expected_rate:25.5,confirmed:true},approveRequest=randomUUID();
 const approved=await save('ops','approve',approval,approveRequest);check(approved.status==='approved','Operations approval');
 check((await save('ops','approve',approval,approveRequest)).version===approved.version,'Approval retry');
 await rejects(()=>save('a','approve',approval),/changed/);
 await rejects(()=>save('worker','save',{...corrected,version:approved.version}),/locked/);
 await rejects(()=>save('a','return',{id:w.id,version:approved.version,reason:'Change approved hours'}),/Only submitted/);
 check(Number((await snap('ops')).sheets[0].gross_estimate)===408,'Approved pay');
 await db.exec('reset role');await db.query('update public.staff_members set hourly_rate=30 where id=$1',[worker.id]);
 check(Number((await snap('a')).sheets[0].hourly_rate)===25.5,'Approved rate frozen');
 check(Number((await snap('a')).sheets[0].gross_estimate)===408,'Approved estimate frozen');
 for(const who of ['worker','supervisor','b'])for(const table of ['timesheet_pay','timesheet_events'])check((await asUser(db,ids[who],`select * from public.${table}`)).rows.length===0,'No raw private data '+who+' '+table);
 for(const table of ['timesheets','timesheet_pay','timesheet_events']){
  await rejects(()=>asUser(db,ids.a,`delete from public.${table}`),/permission denied/);
  await rejects(()=>asUser(db,ids.worker,`update public.${table} set organisation_id=$1`,[ids.orgB]),/permission denied/);
 }
 const events=(await hist('worker',w.id)).events;check(events.length===4,'Submit/return/resubmit/approval history');check(events.every(e=>!('actor_id' in e)&&!('entries' in e)),'Sanitised owner history');
 const supervisorDraft={...draft,entries:[{date:week,hours:8}]};
 const supDraft=await save('supervisor','save',supervisorDraft);check((await snap('worker')).sheets.length===1,'Still only own sheet');check((await snap('supervisor')).sheets.length===1,'Supervisor only own sheet');check((await snap('ops')).sheets.length===2,'Office all sheets');
 const supSubmitted=await save('supervisor','submit',{...supervisorDraft,id:supDraft.id,version:supDraft.version,confirmed:true});
 await db.exec('reset role');await db.query('update public.staff_members set hourly_rate=null where id=$1',[supervisor.id]);
 await rejects(()=>save('a','approve',{id:supSubmitted.id,version:supSubmitted.version,expected_rate:null,confirmed:true}),/hourly rate in Staff/);
 await db.exec('reset role');await db.query('update public.staff_members set hourly_rate=0 where id=$1',[supervisor.id]);
 const supApproved=await save('a','approve',{id:supSubmitted.id,version:supSubmitted.version,expected_rate:0,confirmed:true});check(supApproved.status==='approved','Admin can approve explicit zero rate');
 await db.exec('reset role');
 const policies=await db.query("select relname,relrowsecurity from pg_class where relnamespace='public'::regnamespace and relname in ('timesheets','timesheet_pay','timesheet_events')");check(policies.rows.length===3&&policies.rows.every(r=>r.relrowsecurity),'All new tables have RLS');
 const grants=await db.query("select proname,proconfig,has_function_privilege('anon',oid,'execute') as anon_access,has_function_privilege('authenticated',oid,'execute') as member_access from pg_proc where pronamespace='public'::regnamespace and proname in ('timesheets_snapshot','timesheet_history','timesheet_save')");check(grants.rows.length===3&&grants.rows.every(r=>!r.anon_access&&r.member_access&&r.proconfig.some(c=>c.startsWith('search_path='))),'Explicit RPC grants and search paths');
 await rejects(()=>snap('platform'),/Active company/);
 await db.exec('reset role');await db.query('update public.organisation_memberships set is_active=false where user_id=$1',[ids.worker]);await rejects(()=>snap('worker'),/Active company/);
 await db.exec('reset role');await db.query('delete from auth.users where id=$1',[ids.worker]);
 const retained=(await snap('ops')).sheets.find(s=>s.id===w.id);check(retained&&retained.owner_user_id===null&&Number(retained.gross_estimate)===408,'Account deletion preserves approved record and pay');
 await db.exec('reset role');await db.query("update public.organisations set status='suspended' where id=$1",[ids.orgA]);await rejects(()=>snap('ops'),/Active company/);
 await db.exec("reset role;set role anon;select set_config('request.jwt.claim.sub','',false)");await rejects(()=>db.query('select public.timesheets_snapshot($1)',[week]),/permission denied/);
 console.log(`PASS timesheets: ${count} assertions (isolated PostgreSQL).`);
}catch(error){console.error(`FAIL timesheets after ${count} assertions: ${error.message}`);process.exitCode=1}finally{await db.close()}
