import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createDatabase,ids,rpcAs,asUser} from './workspace-db.mjs';
process.env.C360_TEST_V15='1';
const db=await createDatabase();let count=0;
const check=(value,message)=>{assert.ok(value,message);count++};
const rejects=async(fn,pattern)=>{await assert.rejects(fn,pattern);count++};
const save=(who,kind,data,request=randomUUID())=>rpcAs(db,ids[who],'vehicle_save',[kind,JSON.stringify(data),request]);
const snap=who=>rpcAs(db,ids[who],'vehicles_snapshot');
const history=(who,id,offset=0)=>rpcAs(db,ids[who],'vehicle_history',[id,offset]);
const vehicle={registration:'AB12 CDE',name:'Fleet van',mileage:100,version:0,vehicle_type:'Van',availability:'Available',notes:'Company-wide vehicle notes'};
const checks=Object.fromEntries(['tyres','lights','brakes','steering','mirrors','wipers','horn','fluids','body_load','seatbelts','other'].map(k=>[k,'pass']));
try{
 const request=randomUUID(),v=await save('a','vehicle',vehicle,request);
 check((await save('a','vehicle',vehicle,request)).id===v.id,'Idempotent create');
 await rejects(()=>save('a','vehicle',{...vehicle,name:'Changed'},request),/Request changed/);
 check((await snap('a')).vehicles.length===1,'One vehicle');
 for(const who of ['a','ops','supervisor','worker'])check((await snap(who)).vehicles[0].id===v.id,who+' can view fleet');
 check((await snap('b')).vehicles.length===0,'Company B cannot see A');
 await rejects(()=>history('b',v.id),/unavailable/);
 for(const who of ['worker','supervisor'])await rejects(()=>save(who,'vehicle',vehicle),/Admin or Operations/);
 await rejects(()=>snap('platform'),/Active company/);
 await rejects(()=>save('ops','vehicle',vehicle),/unique|duplicate/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'ab12cde'}),/unique|duplicate/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'ZZ99ZZZ',organisation_id:ids.orgB}),/assigned by the server/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'DATE1',mot_date:'infinity'}),/check constraint/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'LENGTH1',name:'x'.repeat(161)}),/check constraint/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'BADRATE',mileage:-1}),/check constraint/);
 await rejects(()=>save('a','vehicle',{...vehicle,registration:'BADSTAFF',assigned_staff_id:randomUUID()}),/active staff/);
 const b=await save('b','vehicle',{...vehicle,name:'Company B van'});
 const inspect={id:v.id,mileage:101,checks,confirmed:true};
 for(const who of ['a','ops','supervisor','worker']){const r=await save(who,'inspection',inspect);check(!r.has_defects,who+' inspected');}
 let h=await history('worker',v.id);check(h.total===4,'All roles saved inspection');
 check(h.inspections.every(i=>i.registration===vehicle.registration&&i.inspector_id&&i.submitted_at),'Server sets identity/time/registration');
 await rejects(()=>save('worker','inspection',{...inspect,id:b.id}),/unavailable/);
 await rejects(()=>save('worker','inspection',{...inspect,inspector_id:ids.a}),/assigned by the server/);
 await rejects(()=>save('worker','inspection',{...inspect,mileage:100}),/at least/);
 await rejects(()=>save('worker','inspection',{...inspect,mileage:'101.5'}),/invalid input/);
 await rejects(()=>save('worker','inspection',{...inspect,confirmed:false}),/Confirm/);
 await rejects(()=>save('worker','inspection',{...inspect,checks:{}}),/every/);
 await rejects(()=>save('worker','inspection',{...inspect,checks:{...checks,tyres:'unknown'}}),/every/);
 await rejects(()=>save('worker','inspection',{...inspect,checks:Object.fromEntries(Object.keys(checks).map(k=>[k,'na']))}),/assessed/);
 await rejects(()=>save('worker','inspection',{...inspect,checks:{...checks,tyres:'fail'}}),/Describe/);
 await rejects(()=>save('worker','inspection',{...inspect,defect_details:'Defect not marked'}),/Mark a check/);
 const fail={...inspect,checks:{...checks,tyres:'fail'},defect_details:'Tyre damaged'},failRequest=randomUUID();
 const failed=await save('worker','inspection',fail,failRequest);
 check((await save('worker','inspection',fail,failRequest)).id===failed.id,'Inspection retry idempotent');
 check((await snap('supervisor')).vehicles[0].open_defects===1,'Defect visible');
 await save('supervisor','inspection',inspect);
 check((await snap('a')).vehicles[0].open_defects===1,'Clear check does not clear defect');
 h=await history('a',v.id);const defect=h.defects[0];
 for(const who of ['worker','supervisor'])await rejects(()=>save(who,'resolve',{id:defect.id,resolution:'Done',confirmed:true}),/Admin or Operations/);
 await rejects(()=>save('b','resolve',{id:defect.id,resolution:'Done',confirmed:true}),/unavailable/);
 await rejects(()=>save('a','resolve',{id:defect.id,resolution:'',confirmed:true}),/action taken/);
 await rejects(()=>save('a','resolve',{id:defect.id,resolution:'Done',confirmed:false}),/confirm/);
 const resolution={id:defect.id,resolution:'Tyre replaced and checked',confirmed:true},resolveRequest=randomUUID();
 await save('ops','resolve',resolution,resolveRequest);await save('ops','resolve',resolution,resolveRequest);
 check((await snap('worker')).vehicles[0].open_defects===0,'Operations resolved');
 check((await history('worker',v.id)).inspections.find(i=>i.id===failed.id).has_defects,'Original inspection unchanged');
 check((await history('a',v.id)).defects[0].resolved_by===ids.ops,'Resolver recorded');
 await rejects(()=>save('a','resolve',resolution),/already resolved/);
 for(const table of ['vehicles','vehicle_inspections','vehicle_defects']){
  check((await asUser(db,ids.b,`select * from public.${table} where organisation_id=$1`,[ids.orgA])).rows.length===0,'RLS '+table);
  await rejects(()=>asUser(db,ids.a,`delete from public.${table}`),/permission denied/);
  await rejects(()=>asUser(db,ids.a,`update public.${table} set organisation_id=$1`,[ids.orgB]),/permission denied/);
 }
 let row=(await snap('a')).vehicles[0];
 await rejects(()=>save('a','vehicle',{...vehicle,id:v.id,version:1}),/changed/);
 await save('ops','archive',{id:v.id,version:row.version,archived:true});
 await rejects(()=>save('worker','inspection',inspect),/Archived/);
 check((await history('worker',v.id)).total===6,'Archived history preserved');
 row=(await snap('a')).vehicles[0];await save('a','archive',{id:v.id,version:row.version,archived:false});
 row=(await snap('a')).vehicles[0];await save('ops','vehicle',{...vehicle,id:v.id,version:row.version,mileage:101,availability:'Unavailable'});
 await save('worker','inspection',inspect);
 check((await snap('worker')).vehicles[0].availability==='Unavailable','Clear check does not change availability');
 const openAgain=await save('a','inspection',fail);
 for(let n=0;n<26;n++)await save('worker','inspection',inspect);
 const first=await history('worker',v.id),second=await history('worker',v.id,25);
 check(first.inspections.length===25&&second.inspections.length===9,'History pagination retains older inspections');
 check(!first.inspections.some(i=>second.inspections.some(j=>j.id===i.id)),'History pages do not overlap');
 check(first.defects.some(d=>d.inspection_id===openAgain.id&&!d.resolved_at),'Older open defects are always visible');
 await rejects(()=>history('worker',v.id,-1),/unavailable/);
 await db.exec('reset role');
 const secured=await db.query("select relname,relrowsecurity from pg_class where relnamespace='public'::regnamespace and relname in ('vehicles','vehicle_inspections','vehicle_defects')");
 check(secured.rows.length===3&&secured.rows.every(r=>r.relrowsecurity),'All new tables have RLS');
 const grants=await db.query("select proname,prosecdef,proconfig,has_function_privilege('anon',oid,'execute') as anon_access,has_function_privilege('authenticated',oid,'execute') as member_access from pg_proc where pronamespace='public'::regnamespace and proname in ('vehicles_snapshot','vehicle_history','vehicle_save')");
 check(grants.rows.length===3&&grants.rows.every(r=>r.prosecdef&&!r.anon_access&&r.member_access&&r.proconfig.some(c=>c.startsWith('search_path='))),'RPC security configuration');
 await db.query('update auth.users set email_confirmed_at=null where id=$1',[ids.worker]);
 await rejects(()=>save('worker','inspection',inspect),/Active company/);
 await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[ids.worker]);
 await db.exec('reset role');await db.query('update public.organisation_memberships set is_active=false where user_id=$1',[ids.worker]);
 await rejects(()=>snap('worker'),/Active company/);await rejects(()=>save('worker','inspection',inspect),/Active company/);
 await db.exec('reset role');await db.query("update public.organisations set status='suspended' where id=$1",[ids.orgA]);
 await rejects(()=>snap('a'),/Active company/);await rejects(()=>save('ops','inspection',inspect),/Active company/);
 await db.exec("reset role;set role anon;select set_config('request.jwt.claim.sub','',false)");
 await rejects(()=>db.query('select public.vehicles_snapshot()'),/permission denied/);
 console.log(`PASS vehicles: ${count} assertions (real PostgreSQL engine, local auth fixtures)`);
}finally{await db.close()}
