-- Construct360 authentication / organisation foundation
-- Supabase/PostgreSQL-compatible migration.
-- Run once in the Supabase SQL Editor as the project owner, or with `supabase db push`.

begin;

create extension if not exists pgcrypto with schema extensions;

do $migration$
begin
  create type public.app_role as enum (
    'admin',
    'operations',
    'supervisor',
    'operative'
  );
exception
  when duplicate_object then null;
end
$migration$;

create table if not exists public.organisations (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 2 and 160),
  slug text unique,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organisation_memberships (
  id uuid primary key default extensions.gen_random_uuid(),
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null default 'operative'::public.app_role,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint one_construct360_company_per_user unique (user_id),
  constraint unique_company_user unique (organisation_id, user_id)
);

create table if not exists public.user_activity_log (
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists organisation_memberships_org_idx
  on public.organisation_memberships (organisation_id);

create index if not exists activity_org_created_idx
  on public.user_activity_log (organisation_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
  new.updated_at := now();
  return new;
end
$function$;

drop trigger if exists organisations_set_updated_at on public.organisations;
create trigger organisations_set_updated_at
before update on public.organisations
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists memberships_set_updated_at on public.organisation_memberships;
create trigger memberships_set_updated_at
before update on public.organisation_memberships
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(btrim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), '')
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      updated_at = now();

  return new;
end
$function$;

drop trigger if exists on_auth_user_created_construct360 on auth.users;
create trigger on_auth_user_created_construct360
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_auth_user();

-- Backfill a profile for any Auth user created before this migration.
insert into public.profiles (id, email, full_name)
select
  u.id,
  coalesce(u.email, ''),
  nullif(btrim(coalesce(u.raw_user_meta_data ->> 'full_name', '')), '')
from auth.users as u
on conflict (id) do update
set email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    updated_at = now();

create or replace function public.is_org_member(p_org uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
  select exists (
    select 1
    from public.organisation_memberships as m
    where m.organisation_id = p_org
      and m.user_id = (select auth.uid())
      and m.is_active
  );
$function$;

create or replace function public.is_org_admin(p_org uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
  select exists (
    select 1
    from public.organisation_memberships as m
    where m.organisation_id = p_org
      and m.user_id = (select auth.uid())
      and m.is_active
      and m.role = 'admin'::public.app_role
  );
$function$;

create or replace function public.current_organisation_id()
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
  select m.organisation_id
  from public.organisation_memberships as m
  where m.user_id = (select auth.uid())
    and m.is_active
  limit 1;
$function$;

create or replace function public.create_organisation_and_admin(p_name text)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_org uuid;
  v_uid uuid := auth.uid();
  v_name text := btrim(p_name);
  v_email text;
  v_full_name text;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;

  if v_name is null or char_length(v_name) < 2 or char_length(v_name) > 160 then
    raise exception using errcode = '22023',
      message = 'Company name must be between 2 and 160 characters';
  end if;

  -- The unique(user_id) constraint is the final concurrency-safe guard.
  if exists (
    select 1
    from public.organisation_memberships as m
    where m.user_id = v_uid
  ) then
    raise exception using errcode = '23505',
      message = 'This account already belongs to a company';
  end if;

  select
    coalesce(u.email, ''),
    nullif(btrim(coalesce(u.raw_user_meta_data ->> 'full_name', '')), '')
  into v_email, v_full_name
  from auth.users as u
  where u.id = v_uid;

  if not found then
    raise exception using errcode = '42501', message = 'Authenticated user was not found';
  end if;

  insert into public.profiles (id, email, full_name)
  values (v_uid, v_email, v_full_name)
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      updated_at = now();

  insert into public.organisations (name, created_by)
  values (v_name, v_uid)
  returning id into v_org;

  insert into public.organisation_memberships (
    organisation_id,
    user_id,
    role,
    is_active,
    created_by
  )
  values (v_org, v_uid, 'admin'::public.app_role, true, v_uid);

  insert into public.user_activity_log (
    organisation_id,
    actor_user_id,
    event_type,
    description
  )
  values (
    v_org,
    v_uid,
    'organisation_created',
    'Created company workspace and first Admin membership'
  );

  return v_org;
end
$function$;

-- Functions are executable by PUBLIC unless explicitly revoked.
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
revoke all on function public.is_org_member(uuid) from public, anon;
revoke all on function public.is_org_admin(uuid) from public, anon;
revoke all on function public.current_organisation_id() from public, anon;
revoke all on function public.create_organisation_and_admin(text) from public, anon;

grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.is_org_admin(uuid) to authenticated;
grant execute on function public.current_organisation_id() to authenticated;
grant execute on function public.create_organisation_and_admin(text) to authenticated;

grant usage on schema public to authenticated;
grant select, update on table public.organisations to authenticated;
grant select, update on table public.profiles to authenticated;
grant select, update on table public.organisation_memberships to authenticated;
grant select, insert on table public.user_activity_log to authenticated;
grant usage, select on sequence public.user_activity_log_id_seq to authenticated;

alter table public.organisations enable row level security;
alter table public.profiles enable row level security;
alter table public.organisation_memberships enable row level security;
alter table public.user_activity_log enable row level security;

drop policy if exists "members view organisation" on public.organisations;
create policy "members view organisation"
on public.organisations
for select
to authenticated
using (public.is_org_member(id));

drop policy if exists "admins update organisation" on public.organisations;
create policy "admins update organisation"
on public.organisations
for update
to authenticated
using (public.is_org_admin(id))
with check (public.is_org_admin(id));

drop policy if exists "profile visibility" on public.profiles;
create policy "profile visibility"
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or exists (
    select 1
    from public.organisation_memberships as target
    where target.user_id = profiles.id
      and public.is_org_admin(target.organisation_id)
  )
);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles
for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists "membership visibility" on public.organisation_memberships;
create policy "membership visibility"
on public.organisation_memberships
for select
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_org_admin(organisation_id)
);

drop policy if exists "admins update memberships" on public.organisation_memberships;
create policy "admins update memberships"
on public.organisation_memberships
for update
to authenticated
using (public.is_org_admin(organisation_id))
with check (public.is_org_admin(organisation_id));

drop policy if exists "activity visibility" on public.user_activity_log;
create policy "activity visibility"
on public.user_activity_log
for select
to authenticated
using (
  actor_user_id = (select auth.uid())
  or public.is_org_admin(organisation_id)
);

drop policy if exists "members insert activity" on public.user_activity_log;
create policy "members insert activity"
on public.user_activity_log
for insert
to authenticated
with check (
  actor_user_id = (select auth.uid())
  and public.is_org_member(organisation_id)
);

-- Deliberately no client INSERT policy for organisations or memberships.
-- Initial onboarding uses create_organisation_and_admin(); invitations use the
-- service-role Edge Function after it verifies an active Admin caller.

commit;
